data:extend({
    {
        type = "int-setting",
        name = "ru-reach-distance",
        --order = "ce",
        setting_type = "startup",
        default_value = 6,
        minimum_value = 1,
        maximum_value = 100000,
    },
    {
        type = "int-setting",
        name = "ru-mine-reach",
        --order = "cf",
        setting_type = "startup",
        default_value = 6,
        minimum_value = 1,
        maximum_value = 100000,
    },
    {
        type = "double-setting",
        name = "ru-mining-speed",
        --order = "cg",
        setting_type = "startup",
        default_value = 1,
        minimum_value = 0.01,
        maximum_value = 1000,
    },
    {
        type = "double-setting",
        name = "ru-running-speed",
        --order = "cib",
        setting_type = "startup",
        default_value = 1,
        minimum_value = 0.01,
        maximum_value = 1000,
    },
    {
        type = "int-setting",
        name = "ru-hp",
        --order = "ch",
        setting_type = "startup",
        default_value = 250,
        minimum_value = 1,
        maximum_value = 250000,
    },
    {
        type = "double-setting",
        name = "ru-hp-recovery",
        --order = "cia",
        setting_type = "startup",
        default_value = 1,
        minimum_value = 0.01,
        maximum_value = 1000,
    },
    {
        type = "int-setting",
        name = "ru-inventory-size",
        --order = "ca",
        setting_type = "startup",
        default_value = 80,
        minimum_value = 20,
        maximum_value = 2000,
    }
})